import type { Metadata } from "next";
import "./globals.css";
import Providers from "./providers";
import { Toaster } from "sonner";
import { LoadingProvider } from "@/context/LoadingContext";
import AppLayout from "./AppLayout/AppLayout";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`h-full antialiased`}>
      <body className="min-h-full flex flex-col">
        <Providers>
          <LoadingProvider>
            <AppLayout>{children}</AppLayout>
          </LoadingProvider>
          <Toaster />
        </Providers>
      </body>
    </html>
  );
}
